/**
 * Everything design-sync's converter needs that this repo doesn't build on its
 * own. Run before package-build.mjs (it is the config's `buildCmd`).
 *
 * Two artifacts:
 *
 *  1. A declaration tree. The converter reads `<Name>Props` out of a shipped
 *     .d.ts, and an app has none -- without this every component's contract
 *     degrades to `[key: string]: unknown`, which is what the design agent
 *     would then code against. `dist/types` is one of the roots the converter
 *     probes, and `index.d.ts` is the entry it resolves exports from, so the
 *     pair is discovered with no package.json change.
 *
 *  2. The compiled stylesheet (see build-css.mjs).
 */
import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");

const run = (cmd, args) => {
  const r = spawnSync(cmd, args, { cwd: ROOT, stdio: "inherit", shell: false });
  if (r.status !== 0) {
    console.error(`prepare: ${cmd} ${args.join(" ")} failed (${r.status})`);
    process.exit(r.status ?? 1);
  }
};

run("npx", ["tsc", "-p", ".design-sync/tsconfig.dts.json"]);

// The converter resolves the package's type entry as <root>/index.d.ts. Point
// it at the emitted barrel so the export surface it sees is exactly entry.ts's.
writeFileSync(
  join(ROOT, "index.d.ts"),
  '// Generated by .design-sync/prepare.mjs -- the type entry design-sync reads.\n' +
    'export * from "./dist/types/.design-sync/entry";\n',
);

run("node", [".design-sync/build-css.mjs"]);
